# Change these first
owner: nandosb # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: WinePass
    url: https://www.winepass.com.ar
    maxResponseTime: 8000
    assignees:
      - nandosb
  - name: NotWorkingSite
    url: https://www.send-alert-not-working-site.com.ar

    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/nandosb/upptime/master/assets/logo-winepass-lila.svg
  name: Upptime
  introTitle: "**WinePass** uptime monitor and status page."
  introMessage: Overall service availability
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

robotsText: "User-agent: * \n Disallow: /"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
